import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/router'
// import Image from 'next/image'
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
  // Redirect to a different page

  
export default function Home() {
    const router = useRouter();

    const index = () => {
        router.push('/');
      };

  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-white dark:bg-white">
  <div className="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
      <a href="#" className="flex items-center mb-6 text-2xl font-semibold text-dark dark:text-black">
          <img className="w-8 h-8 mr-2" src="../logo.png" alt="logo" />
          VectorCrop    
      </a>
      <div className="w-full bg-white rounded-lg shadow dark:border md:mt-0 dark:border-2 sm:max-w-md xl:p-0 dark:bg-white dark:border-gray-900">
          <div className="p-6 space-y-4 md:space-y-6 sm:p-8">
              <h1 className="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-black">
                  Welcome Back Dear
              </h1>
              <form className="space-y-4 md:space-y-6" action="#">
                  <div>
                      <label  className="block mb-2 text-sm font-medium text-gray-900 dark:text-black">Your email</label>
                      <input type="email" name="email" id="email" className="border-2 
                       bg-dark border border-gray-300 text-gray-900 sm:text-sm rounded-lg  block w-full p-2.5 dark:bg-white dark:border-gray-600 dark:placeholder-gray-400 dark:text-dark focus:outline outline-offset-2 outline-cyan-500 " placeholder="name@company.com" />
                  </div>
                  <div>
                      <label  className="block mb-2 text-sm font-medium text-gray-900 dark:text-black">Password</label>
                      <input type="password" name="password" id="password" placeholder="••••••••" className="border-2 
                       bg-dark border border-gray-300 text-gray-900 sm:text-sm rounded-lg  block w-full p-2.5 dark:bg-white dark:border-gray-600 dark:placeholder-gray-400 dark:text-dark focus:outline outline-offset-2 outline-red-500 " />
                  </div>
              
                  <div className="flex items-start">
                      <div className="flex items-center h-5">
                        <input id="terms" aria-describedby="terms" type="checkbox" className="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800" />
                      </div>
                      <div className="ml-3 text-sm">
                        <label  className="font-light text-gray-500 dark:text-gray-300">I accept the <a className="font-medium text-primary-600 hover:underline dark:text-primary-500" href="#">Terms and Conditions</a></label>
                      </div>
                  </div>
                  <button  onClick={index} className="
                  hover:text-white hover:bg-blue-600 transition delay-100 
                  w-full text-white bg-black hover:bg-primary-200 focus:ring-4 focus:outline-none focus:ring-danger-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-200 dark:focus:ring-primary-800">Create an account</button>

                  <p className="text-sm font-light text-center text-gray-500 dark:text-gray-400">
                      Don't have an account? <a href="/auth/signup"  className="font-medium text-primary-600 hover:underline dark:text-primary-500">Sign Up</a>
                  </p>
              </form>
          </div>
      </div>
  </div>
</section>
    </>
  )
}
