import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/router'
// import Image from 'next/image'
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
  // Redirect to a different page

  
export default function Home() {
    const router = useRouter();

    const index = () => {
        router.push('/');
      };

  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style jsx>{`
      .py-20 {
    padding-top: 5rem;
    padding-bottom: auto;

}
`}</style>
      <section className="bg-white dark:bg-white">
  <div className="flex flex-col items-center justify-center px-6 py-20 mx-auto md:h-screen lg:py-8 bg-white dark:bg-white">
      {/* <a href="#" className="flex font-sans items-center mb-6 text-2xl font-semibold text-dark dark:text-black">
          <img className="w-8 h-8 mr-2" src="../logo.png" alt="logo" />
          VectorCrop    
      </a> */}
      <div className="w-full bg-white rounded-lg shadow border md:mt-0 border-2 sm:max-w-md xl:p-0 bg-white border-gray-900 dark:border md:mt-0 dark:border-2 sm:max-w-md xl:p-0 dark:bg-white dark:border-gray-900">
          <div className="border-black p-6 space-y-4 md:space-y-6 sm:p-8">
              <h1 className="text-xl font-mabry font-bold leading-tight text-center tracking-tight text-gray-900 md:text-2xl dark:text-black">
                  Welcome Back!
              </h1>
              <form className="space-y-4 md:space-y-6" action="#">
                
                <div>
                <label htmlFor="UserEmail" className="relative block overflow-hidden rounded-md border-2 border-black px-3 pt-3 shadow-sm focus-within:border-blue-600 focus-within:ring-1 focus-within:ring-blue-600">
                <input type="email" id="UserEmail" placeholder="Email" className="peer h-8 w-full border-none bg-transparent p-0 placeholder-transparent focus:border-transparent focus:outline-none focus:ring-0 sm:text-sm text-black"/>
                 <span className="absolute left-3 top-3 -translate-y-1/2 text-xs text-gray-700 transition-all peer-placeholder-shown:top-1/2 peer-placeholder-shown:text-sm peer-focus:top-3 peer-focus:text-xs">
                   Email
                 
                  </span>
                </label>
                </div>
                
                <div>
                <label htmlFor="Pass" className="relative block overflow-hidden rounded-md border-2 border-black px-3 pt-3 shadow-sm focus-within:border-blue-600 focus-within:ring-1 focus-within:ring-blue-600">
                <input type="password" id="Pass" placeholder="Password" className="peer h-8 w-full border-none bg-transparent p-0 placeholder-transparent focus:border-transparent focus:outline-none focus:ring-0 sm:text-sm text-black"/>
                 <span className="absolute left-3 top-3 -translate-y-1/2 text-xs text-gray-700 transition-all peer-placeholder-shown:top-1/2 peer-placeholder-shown:text-sm peer-focus:top-3 peer-focus:text-xs">
                   Password
                  </span>
                </label>
                </div>
                
                  
              
                  <div className="flex items-start">
                      <div className="flex items-center h-5">
                        <input id="terms" aria-describedby="terms" type="checkbox" className="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-50 dark:border-gray-300 dark:focus:ring-primary-600 dark:ring-offset-gray-800" />
                      </div>
                      <div className="ml-3 text-sm">
                        <label  className="font text-black dark:text-black">I accept the <a className="font-medium text-primary-500 hover:underline dark:text-primary-500" href="#">Terms and Conditions</a></label>
                      </div>
                  </div>

         

                  <a title="" className="group relative block h-full bg-white before:absolute before:inset-0 before:rounded-lg before:border-2 before:border-dashed before:border-gray-900 dark:bg-white dark:before:border-gray-700" href="/">
                    <div className="hover:text-white hover:bg-blue-600 transition delay-100  rounded-lg border-2 border-gray-900 bg-black transition group-hover:-translate-x-2 group-hover:-translate-y-2 dark:border-gray-700 dark:bg-black">
                      <div className="text-center p-2">
                        <h3 className=" text-lg font-medium text-white dark:text-white">Sign in</h3></div></div></a>

                  <p className="text-sm font text-center text-black dark:text-black">
                      Don't have an account? <a href="/auth/signup"  className="font-medium text-primary-600 hover:underline dark:text-primary-500">Sign Up</a>
                  </p>
              </form>
          </div>
      </div>
  </div>
</section>
    </>
  )
}
