import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useRouter } from 'next/router'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();

    const index = () => {
      router.push('/');
    };
    const signup = () => {
      router.push('/auth/signup');
    };
    const signin = () => {
      router.push('/auth/signin');
    };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-gray-900 text-white">
  <div
    className="mx-auto max-w-screen-xl px-4 py-32 lg:flex lg:h-screen lg:items-center"
  >
    <div className="mx-auto max-w-3xl text-center">
      <h1
        className="bg-gradient-to-r from-green-300 via-blue-500 to-purple-600 bg-clip-text text-3xl font-extrabold text-transparent sm:text-5xl"
      >
        Meet your future

        <span className="sm:block"> Goals with VectorCrop. </span>
      </h1>

      <p className="mx-auto mt-4 max-w-xl sm:text-xl sm:leading-relaxed">
      We will deliver you marketing and technology solutions in the best way.
      </p>

      <div className="mt-8 flex flex-wrap justify-center gap-4">
        <a
          className="block w-full rounded border border-blue-600 bg-blue-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-white focus:outline-none focus:ring active:text-opacity-75 sm:w-auto"
          href="/auth/signin"
        >
          Sign in
        </a>

        <a
          className="block w-full rounded border border-blue-600 px-12 py-3 text-sm font-medium text-white hover:bg-blue-600 focus:outline-none focus:ring active:bg-blue-500 sm:w-auto"
          href="/auth/signup"
        >
          Sign Up
        </a>
        <a className="group relative inline-block rounded border text-sm font-medium text-blue-600 focus:outline-none focus:ring active:text-indigo-500" href="/download">
  <span className="absolute rounded border inset-0 translate-x-0 translate-y-0 bg-blue-600 transition-transform group-hover:translate-y-1 group-hover:translate-x-1"></span>

  <span className="relative block rounded border  bg-black hover:bg-red px-8 py-3">
    Download
  </span>
</a>
      </div>
    </div>
  </div>
</section>

    </>
  )
}
